on: push
name: Audit and Publish
jobs:
  auditAndPublish:
    name: Audit and Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies and audit and publish
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
          registry-url: 'https://registry.npmjs.org'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - run: npm ci
      - run: npm audit
      - run: npm publish --access public
        if: startsWith(github.ref, 'refs/tags/')
      - name: Create Github Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: felixbrucker/github-actions/publish-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: --name Pledge-Agent
      - name: Post to Discord
        if: startsWith(github.ref, 'refs/tags/')
        uses: felixbrucker/github-actions/post-release-in-discord@master
        env:
          FOXY_DISCORD_WEBHOOK_ID: ${{ secrets.FOXY_DISCORD_WEBHOOK_ID }}
          FOXY_DISCORD_WEBHOOK_TOKEN: ${{ secrets.FOXY_DISCORD_WEBHOOK_TOKEN }}
